// <auto-generated />
using System;
using Friendfolio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FriendFolio.Migrations
{
    [DbContext(typeof(FriendfolioDbContext))]
    [Migration("20260727125803_AddEntryPhotoUrl")]
    partial class AddEntryPhotoUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("FriendFolio.Models.BookAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookQuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookEntryId");

                    b.HasIndex("BookQuestionId");

                    b.ToTable("BookAnswers");
                });

            modelBuilder.Entity("FriendFolio.Models.BookEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MemoryBookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemoryBookId");

                    b.ToTable("BookEntries");
                });

            modelBuilder.Entity("FriendFolio.Models.BookQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemoryBookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemoryBookId");

                    b.ToTable("BookQuestions");
                });

            modelBuilder.Entity("FriendFolio.Models.MemoryBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MemoryBooks");
                });

            modelBuilder.Entity("FriendFolio.Models.BookAnswer", b =>
                {
                    b.HasOne("FriendFolio.Models.BookEntry", "BookEntry")
                        .WithMany("Answers")
                        .HasForeignKey("BookEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FriendFolio.Models.BookQuestion", "BookQuestion")
                        .WithMany()
                        .HasForeignKey("BookQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookEntry");

                    b.Navigation("BookQuestion");
                });

            modelBuilder.Entity("FriendFolio.Models.BookEntry", b =>
                {
                    b.HasOne("FriendFolio.Models.MemoryBook", "MemoryBook")
                        .WithMany("Entries")
                        .HasForeignKey("MemoryBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemoryBook");
                });

            modelBuilder.Entity("FriendFolio.Models.BookQuestion", b =>
                {
                    b.HasOne("FriendFolio.Models.MemoryBook", "MemoryBook")
                        .WithMany("Questions")
                        .HasForeignKey("MemoryBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemoryBook");
                });

            modelBuilder.Entity("FriendFolio.Models.BookEntry", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("FriendFolio.Models.MemoryBook", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
